### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [alistairfink/Grid-Path-Planning-Prototype-For-AUV-Project#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank-you.

**Comment by alistairfink** [comment]
I guess there is no license, but you're free to do whatever you want with this project. Although you might be better off looking up actual examples of path planning algorithms like dijkstra's or A*. I didn't really know what I was doing when I wrote this so I'm not sure how much it will help you.
